### ISSUE TITLE
Cool project

### ISSUE THREAD

**Issue by serapath** [MikeKovarik/platform-detect#1]
Did you test all those cases?

I'd recomend to put each feature into a separate file, so people don't need to include all the code if they only need to test for certain features, but could still require the entire module if they actually want all the features

```js
const log = (name, is) => console.log(`feature: ${name} = ${is ? 'on' : 'off'}`)

Object.entries(require('platform-detect')).forEach(log)
// vs. 
if (require('platform-detect/is-pwa') console.log('pwa: on')
if (require('platform-detect/is-uwp') console.log('uwp: on')
if (require('platform-detect/is-node') console.log('node: on')
// ...
```

**Comment by MikeKovarik** [comment]
Hey, thanks for stopping by.

I'm regularly developing and testing this lib along with a few apps and isomorphic libraries i work on. So yes i test all of the documented cases. Except for cordova (haven't used that one in a while) and the [few other lines](https://github.com/MikeKovarik/platform-detect/blob/master/index.mjs#L47) that i dropped in with a TODO comment.
Writing automated mocha tests is kinda not possible. Though I'd like to figure it out in the future.

Splitting: I made this project (despite existence of many others) because i wanted it to be as smal as possible and at around 1.4kb I think it is. And i wouldn't want to bloat it beyond 2kb. It didn't occur to me that I should split it into dozens of files because a lot of the checks are intertwined or use the same resouce (for example `platform.web` or `hasWindow`). It would result in a lot of files loading each other and excessive ammount of boilerplate code `import X from './x.mjs`. I believe a few millis spent on running the whole script outweighs the disk reads.

Neither way is ideal but i think for now I'm keeping it as a single file though in the futue I'd like to split it by feature groups. Those can be already seen in the source - runtime, os, device features.

**Comment by MikeKovarik** [comment]
With 1.0.0 the detectors are split into multiple files, not by each feature but by group. So there is `os.mjs` with `windows`, `linux`, `macos`, `android`, and then `runtime.mjs` with `node`, `browser`, `pwa`, `uwp`, etc...
