### ISSUE TITLE
Please Transpile to ES5

### ISSUE THREAD

**Issue by robbyemmert** [MikeKovarik/platform-detect#2]
This is an awesome project. It's working great except for one issue:

It doesn't work on older browsers. It exports ES6 code.

The current standard is exporting ES5 (if you want more advanced features like tree shaking, etc, you can export an esm file as well).

Also, it wasn't an issue for me, since your entry file is in the root, but there should technically be a 'main' attribute in package.json specifying where the entry file is for the library.

Thanks!

**Comment by MikeKovarik** [comment]
Hello. thanks for using the library.

It actually already is available as ES5 UMD bundle which is compatible with RequreJS or can be simply included in `<script>`. There's a note about it in Installation paragraph in readme and Usage (second to last code snippet).

There's also a build script to transpile it from ES6 `npm run build`.

`index.js` used to include it in the repo but it was messy so from 2.0 it's not only included in NPM releases. So you can install it and use it like so
```js
<script src="./node_modules/platform-detect/index.js"></script>
```
or get it from https://unpkg.com/platform-detect

Sidenote: I just noticed that with 2.0.3 version i accidentally published not minified version so I'll fix that soon.

Regarding "main": it's a deliberate decision to not include it in package.json because i extensively researched how to do hybrid ESM/CJS module development and last time i checked the best practice was omit both "main" and "module" fields and simply let node module resolution algorithm try .mjs and .js extension. And obviously browsers use work-in-progress hand written import maps instead of package.json.
But like i said, that was the best practise last time i checked. The opinion among Node maintainers keeps changing all the time so this may be outdated and i may have to look into it again.
