### ISSUE TITLE
Object doesn't support property or method 'includes'

### ISSUE THREAD

**Issue by marcustisater** [MikeKovarik/platform-detect#5]
Love the project but got some issues with getting it to work in ie11. I transpiled the module with babel to es5 with webpack for the index.mjs file and got this in the console.

`Object doesn't support property or method 'includes'` in IE11

Any ideas?

Thanks!

**Comment by marcustisater** [comment]
maybe it's regarded with #2 🙂 ?

**Comment by MikeKovarik** [comment]
Hello. Thank You for the interest. I'm glad you like the project :)

I believe the error is related to string.includes() which is a new API and ie11 doesn't support it. I will look into it sometime next week because I'm at a conference now and also very busy with my dayjob.

For now I suggest you use string includes polyfill like this one https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes

PS: in the issue you linked I explained that this package comes in both ES modue as well as UMD bundle that is in ES5 syntax. But it turns out I didn't think about the available API

**Comment by marcustisater** [comment]
@MikeKovarik hope you had a good conference. Thanks a ton for the quick reply, I don't expect you to fix it right away 😄

**Comment by MikeKovarik** [comment]
Hello. I'm so sorry for the late response. I completely forgot about it.
I thought about implementing string.includes and Array.from in the library but I eventually decided not to do that as it would increase lib size.
The end solution is: https://github.com/MikeKovarik/platform-detect#usage-in-older-browsers
